# Generated by Django 4.2.29 on 2026-03-09 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('appetizer', 'Entrée'), ('main_course', 'Plat principal'), ('dessert', 'Dessert'), ('beverage', 'Boisson'), ('soup', 'Soupe'), ('salad', 'Salade')], max_length=20)),
                ('ingredients', models.JSONField(blank=True, default=list)),
                ('image', models.ImageField(blank=True, null=True, upload_to='dishes/')),
                ('is_vegetarian', models.BooleanField(default=False)),
                ('is_vegan', models.BooleanField(default=False)),
                ('is_gluten_free', models.BooleanField(default=False)),
                ('is_spicy', models.BooleanField(default=False)),
                ('is_popular', models.BooleanField(default=False)),
                ('calories', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
